version: '3'

services:
  db:
    environment:
      - POSTGRES_USERNAME=${PICDO_DB_USER}
      - POSTGRES_PASSWORD=${PICDO_DB_PASSWORD}
      - POSTGRES_DATABASE=${PICDO_DB_NAME}
    expose:
      - "${PICDO_DB_PORT}"
    hostname: "${PICDO_DB_HOST}"
    image: postgres:14-alpine
    ports:
      - "${PICDO_DB_PORT}"
    restart: always
    volumes:
      - ./scripts/docker:/docker-entrypoint-initdb.d
  picdo:
    build: '.'
    command: >
      bash -c 'sleep 5;
      python /app/manage.py migrate;
      python /app/manage.py runserver 0.0.0.0:8000;'
    depends_on:
      - db
    environment:
      - PICDO_SECRET_KEY
      - PICDO_ENVIRONMENT
      - PICDO_DB_HOST
      - PICDO_DB_PORT
      - PICDO_DB_USER
      - PICDO_DB_PASSWORD
    image: redbeandock/picdo:${PICDO_VERSION}
    ports:
      - "8000:8000"