# Generated by Django 3.1.4 on 2021-02-17 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, verbose_name='mot de passe')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('image', models.ImageField(upload_to=gallery.models.get_picture_path)),
                ('tags', models.CharField(max_length=200, null=True, verbose_name='tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.user')),
            ],
            options={
                'verbose_name': 'photo',
            },
        ),
    ]
