# Generated by Django 3.1.4 on 2021-02-27 22:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('image', models.ImageField(upload_to=gallery.models.get_picture_path)),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='tags')),
                ('filename', models.CharField(default='Unknown', max_length=200)),
                ('hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['-date'],
            },
        ),
    ]
