# Generated by Django 3.1.4 on 2021-01-31 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picture',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.URLField(),
        ),
    ]
