# Generated by Django 3.1.4 on 2021-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('D', 'Dates'), ('U', 'User'), ('S', 'Special')], default='U', max_length=1, verbose_name='categorie'),
        ),
    ]
