# Generated by Django 3.1.4 on 2021-02-23 14:59

from django.db import migrations
import gallery.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210223_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=gallery.models.get_picture_path),
        ),
    ]
