# Generated by Django 3.1.4 on 2021-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_picture_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
