# Generated by Django 3.1.4 on 2021-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210224_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='filename',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
