# Generated by Django 3.2.4 on 2021-06-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20210528_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='hidden',
        ),
    ]
