# Generated by Django 3.2.4 on 2021-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_picture_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
