# Generated by Django 3.2.9 on 2021-11-06 19:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('category', models.CharField(choices=[('D', 'Dates'), ('U', 'User'), ('S', 'Special')], default='U', max_length=1, verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'album',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réglage utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('image', models.ImageField(upload_to=gallery.models.get_picture_path)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='tags')),
                ('filename', models.CharField(default='Unknown', max_length=200)),
                ('hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(to='gallery.Picture'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
